language: node_js
dist: trusty
node_js: '6'
before_script: npm install
script: npm run transpile
deploy:
  provider: npm
  email: sebastian.lzy@gmail.com
  api_key:
    secure: OKfB5SvTbS/6o7mvfX5wHgrFPaaW3UqGk05ZZ1qtduG1Ji1DyohNUJoX1re9TaEwYIBXs2RrKpbyz9GJ45ujdusB0EfR8ANso9hwNA5Qmh8nBeBbvQxJ+mguVouoBm7CWmBs/89HG/d2lxoOC3jM9xeK8gX/b9BqstrK6EMjlN1FAe7xEZEgh52G2y/QRB/wQOTdmfdSjk+6wO22wEngr53PViCRfrMbO5m5VwyHETm90+lWPQ5cZUaUrYK3NsLlNyb8RGWeioOwk8PWhkea+Vk8YbD002zK7cvbaHmKyXxq5ddRxjhWYgv1m6JubuJ3oYjM6Wgrm3SAdf+A9jtzabelVApPbeOosBlUnpr+ebJgYM3YhRljKoRs3E9I3QL6uMKZ8sWiezZYT59HHvmPHyGJQIDOEi2Cdai80XJNUpO/6FYRRzAKkHsb2I6kne5HE+9Wsbd2O6gJqvVUbAq21rlJZWuguYWsr248FaWtfiR6+l6OSa+NIXKRIqcTvBT1ucs6wH24f7KiLAF52ft942OKr5pXPXXx36YZcd+4KkSLaR4xdLuMl7WciDTCO7gaTaT7v4CQ+mBjywIznn58euTK8WrNeGvhQ2z9exODNbkgAMAONhu3akPEZejGRZ1EtBJQ4v0uF8wGTX6SPhYnsIhU5MS2T6gqGpM/m4dU0B0=
  on:
    repo: sebastianlzy/react-sticky-timer
env:
  global:
    secure: IS2WI8n+QLBCFE78KBtRa0IRaXb+27l4nJ1c63VAE5xMVtHzqoURulPDPxmOYG3LSzslwzNvXnJMm8jA6KMroy3KT6kYdJ9fQKbHkkbV452ekG3sqO/Ji2CSqIcJxYJ2F/AIGgvtI1XnjZTuzRnX+YwacHQRw8Q1yDRvQuHeinKYinzL2W93fTy++CgdTEFAlB0ZDd20atx+LAbXHlvfHcN60pvHUHoGDrCxKTwsZOa7ISExIviSJR0OXp1k+ZjlZADjmegSyjkfjOeg5MD0zEdkidSMzR3uxAafCCkoxM7tWdEV12IULVdY4aB7V3/CcBriNSmP80tolNJeXy0DeAz5PnWEFcIKq0xctzLuj8i2oNNNbTdzlK9ZUW7wEmWnU5JAi67JhHW1zX90KoZRVaeMWHSKdHh7n27fvsASG+FVL7FgxKPOq6FXi8L6yNWGYGuLmv8afEyGUwlkGefoD4vENy1pzBE7ep7KkQtYwLB0q6s82LoaEnlMTkzW1rRYgC7bFcuxzVQMhnNYf7GxHiMaQgD12mJI30NKEk2O8U8Kj3DzvDfZt6yLJkrlB3k0vo1il1zqk5SlKWyn6cOyWSYqIyQDnQaH5Lirnsk6VYktxGEGoxNMmtY7njbGaPce9EynJnnoHN+vrj8sSomP7MerRas+sXJ8n3Bi5PTxPVc=
